### ISSUE TITLE
["Bearer","[object","Object]"]

### ISSUE THREAD

**Issue by omayhemo** [lelylan/simple-oauth2#107]
I use code/server flow.  In ExpressJS I am able to receive the callback and get a token, which I then pass back to the UI.  simple-oauth2 behaves as expected and isAuthenticated() = true.

Whenver I make subsequent http requests, the appended authorization header seems to be wrong.  Instead I see ["Bearer","[object","Object]"]

**Comment by omayhemo** [comment]
Update, the whole thing has taken a dump now.  I took a break hoping for a quick turn around on this q, to find when I returned, every authCode.getToken returns a fatal exception.

No idea what's going on here, and I've burnt too much time on it already.
> "Error: Internal Server Error
    at Object.api (d:\Code\VSTS\automaton\src\server\node_modules\simple-oauth2\lib\core.js:107:8)
    at Object.getToken (d:\Code\VSTS\automaton\src\server\node_modules\simple-oauth2\lib\client\auth-code.js:46:8)
    at d:/Code/VSTS/automaton/src/server/components/authorization/authorization.js:15:28
    at Layer.handle [as handle_request] (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\layer.js:95:5)
    at d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:271:10)
    at d:\Code\VSTS\automaton\src\server\node_modules\scaffi-server-core\lib\core-components\app\app.js:152:5
    at Layer.handle [as handle_request] (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:312:13)
    at d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:271:10)
    at serveStatic (d:\Code\VSTS\automaton\src\server\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:312:13)
    at d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:271:10)
    at urlencodedParser (d:\Code\VSTS\automaton\src\server\node_modules\body-parser\lib\types\urlencoded.js:82:7)
    at Layer.handle [as handle_request] (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:312:13)
    at d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Code\VSTS\automaton\src\server\node_modules\express\lib\router\index.js:271:10)
    at d:\Code\VSTS\automaton\src\server\node_modules\body-parser\lib\read.js:129:5
    at invokeCallback (d:\Code\VSTS\automaton\src\server\node_modules\raw-body\index.js:262:16)
    at done (d:\Code\VSTS\automaton\src\server\node_modules\raw-body\index.js:251:7)"

**Comment by omayhemo** [comment]
_Holy breaking changes batman!!!_
I grabbed your 1.0 version and made the necessary adjustments, but I'm still receiving Internal Server Error in the getToken callback.

I'm very frustrated at this point, and ripping all the simple-oauth2 stuff out of the project and creating my own requests.

**Comment by omayhemo** [comment]
Too many breaking changes in the latest release.  Moving on.

**Comment by jonathansamines** [comment]
Hi @omayhemo, just note that the token being returned is always an object containing the actual token. Let me know if the latest version works for you.

**Comment by omayhemo** [comment]
Latest version works fine.  Thanks.
