### ISSUE TITLE
Geeting error message as Cannot find module 'joi'

### ISSUE THREAD

**Issue by smrutiranjanbehera** [lelylan/simple-oauth2#133]
Though I have installed joi module in the project, Still I am getting this following error message while starting. I have updated node version to the latest one  to 4.6.1

node index.js "index"

module.js:471
    throw err;
    ^

Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\i316655\git\simple-oauth2\index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 start: `node index.js "index"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jonathansamines** [comment]
HI @smrutiranjanbehera how do you installed the project? If it was via `git clone` then you have to `npm install` the module dependencies.

**Comment by jonathansamines** [comment]
Closing due inactivity.

**Comment by asawarik** [comment]
hello i'm having the same problem. can someone help? I did the npm install for the module dependcies

**Comment by Trinitron** [comment]
To fix this problem check out the full "simple-oauth2" repository first (and not just simple-oauth2/example/). and then run npm install command.

**Comment by keshrirai** [comment]
hello i'm having the same problem. can someone help?I did the npm install for the module dependcies but did not work. plz some suggestion
