### ISSUE TITLE
Revoke of access token not working

### ISSUE THREAD

**Issue by guruprasad211** [lelylan/simple-oauth2#149]
Hi 

I would like to revoke the access token when the user is requested

followed the below steps

const tokenObject = {
							'access_token': driveDetls.token.access_token,
							'refresh_token': driveDetls.token.refresh_token,
							'expires_in': '3600'
						  };

// Create the access token wrapper 
						const tokenResp = oneDriveoauth2.accessToken.create(tokenObject);
						// Revoke only the access token
						tokenResp.revoke('access_token', function(error) {
							try {
								logger.MessageQueueLog.info('token revoked.',error);
								// Session ended. But the refresh_token is still valid.						
								// Revoke the refresh_token
								tokenResp.revoke('refresh_token', function(error) {
									logger.MessageQueueLog.info('token revoked.',error);
								});	
							} catch (error) {
								logger.MessageQueueLog.error(error.stack);
							}							
						}); 

i am getting the below response without any proper error message

please any one can help me the same

**Comment by jonathansamines** [comment]
@guruprasad211 Sorry, I am not seeing which error are you getting, do you mind to specify it?

**Comment by guruprasad211** [comment]
its not giving any specifi error, its shown as below

Error
    at data (/home/nowconfer/NowConfer-1.0.1.0/node_modules/simple-oauth2/lib/core.js:91:29)
    at tryCatcher (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/nowconfer/NowConfer-1.0.1.0/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/nowconfer/NowConfer-1.0.1.0/node_modules/request/main.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/nowconfer/NowConfer-1.0.1.0/node_modules/request/main.js:661:16)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)

**Comment by jonathansamines** [comment]
@guruprasad211 Sorry for the late response, I would suggest you to use something like:

```bash
   DEBUG=*simple-oauth2* npm start
```

In order to take a look at the original response from the server.

**Comment by snavarropino** [comment]
Hi, I have same issue. Revoke is not working. In fact, I have captured trafficy and it seems to send a GET instead of a POST

![imagen](https://user-images.githubusercontent.com/11868679/33882779-9cfe67b4-df39-11e7-8c6f-67e353f95ef4.png)

**Comment by jonathansamines** [comment]
@snavarropino That would be really weird, as all requests sent by this library as set to POST. Which version of this library are you using?. Would be possible to create a reduced reproduction for this issue?

**Comment by snavarropino** [comment]
Sure, let me prepare it and I will come back with the code

**Comment by jonathansamines** [comment]
@snavarropino Will close this issue due inactivity. Feel free to re-open with a reproduction example.
