### ISSUE TITLE
AssertionError [ERR_ASSERTION]

### ISSUE THREAD

**Issue by bhushankumarl** [lelylan/simple-oauth2#213]
Unexpected error.

```
/var/www/app/current/node_modules/hoek/lib/index.js:736
    throw new Assert.AssertionError({
    ^

AssertionError [ERR_ASSERTION]: options contain unknown keys: 0,1
    at new AssertionError (internal/errors.js:315:11)
    at Object.exports.assert (/var/www/app/current/node_modules/hoek/lib/index.js:736:11)
    at internals.String.uri (/var/www/app/current/node_modules/joi/lib/types/string/index.js:286:18)
    at Object.<anonymous> (/var/www/app/current/node_modules/simple-oauth2/index.js:22:42)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
```

**Comment by jonathansamines** [comment]
@bhushankumarl Please try upgrading to the latest version. That should fix the error.

**Comment by bhushankumarl** [comment]
@jonathansamines That works. Thank You

**Comment by CExSSoni** [comment]
@bhushankumarl @jonathansamines What did you upgraded in this error

**Comment by jonathansamines** [comment]
@CExSSoni To the latest version available of simple-oauth2.
