### ISSUE TITLE
Crash if state is blank (i.e. '')

### ISSUE THREAD

**Issue by chriskacerguis** [lelylan/simple-oauth2#337]
#### Context

* *node version*:
```sh
❯ node -v
v14.3.0
```

* *module version with issue*:
```sh
❯ more package.json|grep client-oauth2
    "client-oauth2": "^4.3.0",
```

* *last module version without issue*:
n/a (just tried the latested install via npm i client-oauth2)

* *environment* (e.g. node, browser, native):

```
❯ uname -a
Darwin Mac-mini.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

* *any other relevant information*:

Issue is fixed if I remove the `state: '' ` or if I add text `  state: 'hello' ` 

#### What are you trying to achieve or the steps to reproduce?

```javascript
const myoAuth = new ClientOAuth2({
  clientId: 'REMOVED',
  clientSecret: 'REMOVED',
  accessTokenUri: 'https://REMOVED/oauth2/token',
  authorizationUri: 'https://REMOVED/oauth2/authorize',
  redirectUri: 'http://localhost:3000/callback',
  scopes: [],
  state: ''
});
```

#### What was the result you got?

On the callback from the OAuth2 provider the app crashed with the following.

```
(node:5883) UnhandledPromiseRejectionWarning: TypeError: Invalid state: this is hte state
    at CodeFlow.getToken (/Users/REMOVED/Projects/REMOVED/node_modules/client-oauth2/src/client-oauth2.js:610:27)
    at /Users/REMOVED/Projects/REMOVED/index.js:31:18
    at Layer.handle [as handle_request] (/Users/REMOVED/Projects/REMOVED/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/REMOVED/Projects/REMOVED/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/chriskacerguis/Projects/REMOVED/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/REMOVED/Projects/REMOVED/node_modules/express/lib/router/layer.js:95:5)
    at /Users/REMOVED/Projects/REMOVED/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/REMOVED/Projects/REMOVED/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/REMOVED/Projects/t2mqtt/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/REMOVED/Projects/REMOVED/node_modules/express/lib/middleware/init.js:40:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### What result did you expect?

I expected to get the oauth token.

**Comment by chriskacerguis** [comment]
Wow...I'm a moron...wrong repo.
