### ISSUE TITLE
Error requiring the module

### ISSUE THREAD

**Issue by ricxsar** [lelylan/simple-oauth2#345]
#### Context

* *node version*:v10.15.1
* *module version with issue*:4.1.0
* *last module version without issue*:
* *environment* (e.g. node, browser, native):node
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?
I'm just want to use the library but throws an error even just requiring the module.

```js
const some = 'properly formatted code example';
```

#### What was the result you got?
```js
C:\Users\Admin\dockers\heroku-off-load-payment-processing\node_modules\simple-oauth2\lib\client.js:19
  #config = null;
  ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heroku-off-load-payment-processing@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the heroku-off-load-payment-processing@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-26T00_05_46_069Z-debug.log
```

#### What result did you expect?
The module should be usable.

**Comment by jonathansamines** [comment]
@ricxsar Please see the [requirements](https://github.com/lelylan/simple-oauth2#requirements) for v4. If you need to support older node version, please use v3.
