### ISSUE TITLE
Error Response Error: 400 Bad Request

### ISSUE THREAD

**Issue by elliotfisher13** [lelylan/simple-oauth2#347]
#### Context

**node version*: 14.9.0
**module version*: 4.1.0
**environment* (e.g. node, browser, native): 4.1.0node
**any other relevant information*: -

#### How can we help?

Hi guys,

We are trying to use your OAuth client however have had no luck. We keep getting Error 400 : Bad Request whatever we do? Our authorizeURL stage works fine it seems, it just the callback where getToken() is being called.

Here is our config:

```
const { AuthorizationCode } = require("simple-oauth2");

const client = new AuthorizationCode({
  client: {
    id: process.env.GC_CLIENT_ID,
    secret: process.env.GC_CLIENT_SECRET
  },
  auth: {
    authorizeHost: "https://connect-sandbox.gocardless.com",
    authorizePath: "oauth/authorize",
    tokenHost: "https://connect-sandbox.gocardless.com",
    tokenPath: "oauth/access_token"
  }
});

module.exports = client;
```

Here is where we start the OAuth flow:

```
const gocardlessAuth = require("../../gocardless/auth");

router.get("/gocardless/redirect", (req, res) => {
  if (!req.query.user_id) {
    res.status(400).send("cannot find user_id parameter");
    return;
  }

  const url = gocardlessAuth.authorizeURL({
    redirect_uri: "https://api.XXXXX.co.uk/oauth/gocardless/callback",
    scope: "read_write",
    state: req.query.user_id
  });

  res.redirect(url);
});
```

And finally here is the callback function:
```
router.get("/gocardless/callback", async (req, res) => {
  console.log("req.originalUrl", req.originalUrl);

  if (!req.query.state) {
    res.status(400).send("cannot find state parameter");
    return;
  }

  if (!req.query.code) {
    res.status(400).send("cannot find code parameter")
  }

  const tokenParams = {
    code: req.query.code,
    redirect_uri: 'http://api.XXXXX.co.uk/success',
    scope: 'read_write',
  };

  try {
    const user = await gocardlessAuth.getToken({
      client_id: process.env.GC_CLIENT_ID,
      client_secret: process.env.GC_CLIENT_SECRET,
      code: req.query.code,
      state: req.query.state,
      scope: "read_write",
      redirect_uri:
        "https://api.XXXXX.co.uk/oauth/gocardless/callback"
    }); //This is where the error is occurring

    res.status(200).send(user);
  } catch (err) {
    console.error("Error while getting GoCardless tokens:", err);
    res.status(500).send("Error while getting GoCardless tokens");
  }

});
```

Here is our logs:

```
2020-09-05T12:19:11.439997+00:00 app[web.1]: Error while getting GoCardless tokens: Error: Response Error: 400 Bad Request
2020-09-05T12:19:11.439999+00:00 app[web.1]: at internals.Client._shortcut (/app/node_modules/@hapi/wreck/lib/index.js:547:15)
2020-09-05T12:19:11.439999+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-09-05T12:19:11.440000+00:00 app[web.1]: at async Client.request (/app/node_modules/simple-oauth2/lib/client.js:40:22)
2020-09-05T12:19:11.440001+00:00 app[web.1]: at async AuthorizationCode.getToken (/app/node_modules/simple-oauth2/lib/grants/authorization-code.js:50:22)
2020-09-05T12:19:11.440001+00:00 app[web.1]: at async /app/routes/oauth/index.js:41:18 {
2020-09-05T12:19:11.440002+00:00 app[web.1]: data: {
2020-09-05T12:19:11.440003+00:00 app[web.1]: isResponseError: true,
2020-09-05T12:19:11.440003+00:00 app[web.1]: headers: {
2020-09-05T12:19:11.440003+00:00 app[web.1]: date: 'Sat, 05 Sep 2020 12:19:11 GMT',
2020-09-05T12:19:11.440004+00:00 app[web.1]: 'content-type': 'application/json',
2020-09-05T12:19:11.440004+00:00 app[web.1]: 'cache-control': 'no-cache',
2020-09-05T12:19:11.440004+00:00 app[web.1]: 'x-request-id': '0AA40043C8EA_AC1221A51F92_5F53823F_7C766002A',
2020-09-05T12:19:11.440004+00:00 app[web.1]: 'content-length': '85',
2020-09-05T12:19:11.440005+00:00 app[web.1]: 'strict-transport-security': 'max-age=31556926; includeSubDomains; preload',
2020-09-05T12:19:11.440005+00:00 app[web.1]: vary: 'Origin',
2020-09-05T12:19:11.440005+00:00 app[web.1]: 'x-xss-protection': '1; mode=block',
2020-09-05T12:19:11.440006+00:00 app[web.1]: 'x-content-type-options': 'nosniff',
2020-09-05T12:19:11.440006+00:00 app[web.1]: via: '1.1 google',
2020-09-05T12:19:11.440006+00:00 app[web.1]: 'alt-svc': 'clear',
2020-09-05T12:19:11.440006+00:00 app[web.1]: connection: 'close'
2020-09-05T12:19:11.440006+00:00 app[web.1]: },
2020-09-05T12:19:11.440007+00:00 app[web.1]: res: IncomingMessage {
2020-09-05T12:19:11.440007+00:00 app[web.1]: _readableState: [ReadableState],
2020-09-05T12:19:11.440007+00:00 app[web.1]: readable: false,
2020-09-05T12:19:11.440007+00:00 app[web.1]: _events: [Object: null prototype],
2020-09-05T12:19:11.440007+00:00 app[web.1]: _eventsCount: 2,
2020-09-05T12:19:11.440008+00:00 app[web.1]: _maxListeners: undefined,
2020-09-05T12:19:11.440008+00:00 app[web.1]: socket: [TLSSocket],
2020-09-05T12:19:11.440008+00:00 app[web.1]: connection: [TLSSocket],
2020-09-05T12:19:11.440008+00:00 app[web.1]: httpVersionMajor: 1,
2020-09-05T12:19:11.440008+00:00 app[web.1]: httpVersionMinor: 1,
2020-09-05T12:19:11.440008+00:00 app[web.1]: httpVersion: '1.1',
2020-09-05T12:19:11.440009+00:00 app[web.1]: complete: true,
2020-09-05T12:19:11.440009+00:00 app[web.1]: headers: [Object],
2020-09-05T12:19:11.440009+00:00 app[web.1]: rawHeaders: [Array],
2020-09-05T12:19:11.440009+00:00 app[web.1]: trailers: {},
2020-09-05T12:19:11.440009+00:00 app[web.1]: rawTrailers: [],
2020-09-05T12:19:11.440011+00:00 app[web.1]: aborted: false,
2020-09-05T12:19:11.440011+00:00 app[web.1]: upgrade: false,
2020-09-05T12:19:11.440011+00:00 app[web.1]: url: '',
2020-09-05T12:19:11.440011+00:00 app[web.1]: method: null,
2020-09-05T12:19:11.440011+00:00 app[web.1]: statusCode: 400,
2020-09-05T12:19:11.440012+00:00 app[web.1]: statusMessage: 'Bad Request',
2020-09-05T12:19:11.440012+00:00 app[web.1]: client: [TLSSocket],
2020-09-05T12:19:11.440012+00:00 app[web.1]: _consuming: false,
2020-09-05T12:19:11.440012+00:00 app[web.1]: _dumped: false,
2020-09-05T12:19:11.440012+00:00 app[web.1]: req: [ClientRequest],
2020-09-05T12:19:11.440012+00:00 app[web.1]: [Symbol(kCapture)]: false
2020-09-05T12:19:11.440012+00:00 app[web.1]: },
2020-09-05T12:19:11.440013+00:00 app[web.1]: payload: {
2020-09-05T12:19:11.440013+00:00 app[web.1]: error: 'invalid_client',
2020-09-05T12:19:11.440014+00:00 app[web.1]: error_description: 'The provided credentials are invalid'
2020-09-05T12:19:11.440014+00:00 app[web.1]: }
2020-09-05T12:19:11.440014+00:00 app[web.1]: },
2020-09-05T12:19:11.440014+00:00 app[web.1]: isBoom: true,
2020-09-05T12:19:11.440014+00:00 app[web.1]: isServer: false,
2020-09-05T12:19:11.440014+00:00 app[web.1]: output: {
2020-09-05T12:19:11.440015+00:00 app[web.1]: statusCode: 400,
2020-09-05T12:19:11.440015+00:00 app[web.1]: payload: {
2020-09-05T12:19:11.440015+00:00 app[web.1]: statusCode: 400,
2020-09-05T12:19:11.440015+00:00 app[web.1]: error: 'Bad Request',
2020-09-05T12:19:11.440015+00:00 app[web.1]: message: 'Response Error: 400 Bad Request'
2020-09-05T12:19:11.440016+00:00 app[web.1]: },
2020-09-05T12:19:11.440016+00:00 app[web.1]: headers: {}
2020-09-05T12:19:11.440016+00:00 app[web.1]: }
2020-09-05T12:19:11.440016+00:00 app[web.1]: }
```

**Comment by elliotfisher13** [comment]
Any assistance is much appreciated 👍

**Comment by alaarab** [comment]
@elliotfisher13 what was your solution? i am having the same issue

**Comment by elliotfisher13** [comment]
@alaarab Make sure your client ID and secret are 100% copied correctly, I missed a character off my client ID
