### ISSUE TITLE
Error: Schema can only contain plain objects

### ISSUE THREAD

**Issue by AnandDivakaran** [lelylan/simple-oauth2#357]
When i include the below code in my node file and run it, i get the following error:
Any suggestions on what could be the issue ?

Code Snippet: 

const { ClientCredentials } = require('simple-oauth2');

Error Details:

c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\joi\lib\common.js:190
        throw err;
        ^

Error: Schema can only contain plain objects
    at new module.exports (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\@hapi\hoek\lib\assert.js:20:11)
    at Object.internals.schema (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\joi\lib\compile.js:88:5)
    at Object.exports.schema (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\joi\lib\compile.js:17:26)
    at internals.Base.$_compile (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\joi\lib\base.js:645:24)
    at c:\DevWorkspace\ICPWorkspace\InternalUsersFix\IntelCustomerProfile\node_modules\joi\lib\types\keys.js:256:92
    at Object.exports.tryWithPath (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\joi\lib\common.js:176:16)
    at internals.Base.method [as keys] (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\joi\lib\types\keys.js:256:32)
    at Object.<anonymous> (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\simple-oauth2\lib\config.js:9:35)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.wrappedLoad [as _load] (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\newrelic\lib\shimmer.js:373:24)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\simple-oauth2\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.wrappedLoad [as _load] (c:\DevWorkspace\ICPWorkspace\InternalUsersFix\ICP\node_modules\newrelic\lib\shimmer.js:373:24) {
  path: 'id'
}
Process exited with code 1
null: Uncaught Error: Schema can only contain plain objects

**Comment by jonathansamines** [comment]
Hi @AnandDivakaran Please provide a full reproduction example. The error above should not be possible with the snippet you shared.

Feel free to reopen using the default template we provide.
