### ISSUE TITLE
refresh() API does not work

### ISSUE THREAD

**Issue by pathikrit** [lelylan/simple-oauth2#420]
The following piece of code works fine:
```js
const {ClientCredentials} = require('simple-oauth2')

async function test(client_id, client_secret) {
  const credentials = new ClientCredentials({
    client: {id: client_id, secret: client_secret},
    auth: {tokenHost: 'https://portal.getjoan.com', tokenPath: '/api/token/'}
  })
  const accessToken = await credentials.getToken()

  if (true || accessToken.expired()) {   // Emulate token expiry
     accessToken = await credentials.getToken()
  }
}
```

However if I change the last lines to following:
```js
if (true || accessToken.expired()) {   // Emulate token expiry
     accessToken = await accessToken.refresh()
 }
```
I get following error:
```
 throw new Boom.Boom(`Response Error: ${res.statusCode} ${res.statusMessage}`, { statusCode: res.statusCode, data });
              ^

Error: Response Error: 400 Bad Request
    at internals.Client._shortcut (/Users/pbhowmick/workspace/node-joan/node_modules/@hapi/wreck/lib/index.js:569:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.request (/Users/pbhowmick/workspace/node-joan/node_modules/simple-oauth2/lib/client/client.js:39:22)
    at async AccessToken.refresh (/Users/pbhowmick/workspace/node-joan/node_modules/simple-oauth2/lib/access-token.js:49:22) {
```

This might be because the library is putting auth headers for the refresh request (see #32) but #54 was never merged.

**Comment by jonathansamines** [comment]
Hey @pathikrit really hard to tell without a complete reproduction or the details our issues template require, but you can try the following options:

- `options.authorizationMethod=body`  - will send credentials as part of the request's payload
- `options.bodyFormat=?` - really depends on your oauth2 provider

See: https://github.com/lelylan/simple-oauth2/blob/master/API.md#options

I'll close this, but feel free to re-open with a complete reproduction.
