### ISSUE TITLE
simple-oath2 bug: TypeError: Cannot assign to read only property 'expires_at' - with README GitHub example

### ISSUE THREAD

**Issue by sorenp** [lelylan/simple-oauth2#99]
I have installed simple-oauth2. 
I have created my OAuth2 App in GitHub. 
I have taken the [Express and Github example](https://github.com/lelylan/simple-oauth2#express-and-github-example) from the README.MD file and modified it with app ID’s and callback url.

However, when I run it I get a TypeError: Cannot assign to read only property 'expires_at' … (see full trace below).

I have tried adding the workaround line
`result.expires_in = 2592000; // 30 days in seconds`
to the SaveToken function as suggested in [OAuth 2 server should not be required to return "expires_in" attribute #24](https://github.com/lelylan/simple-oauth2/issues/24), but to no avail.

I have tried this with Node version 4.4.5 on my Mac and Node version 4.4.7 on AWS Linux. The result is the same in both cases.

What is the fix for this error please?

Full error trace:

`Express server started on port 3000
/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot assign to read only property 'expires_at' of access_token=55b687c17346ccf22bc7188c3c786c5ad110a97a&scope=notifications&token_type=bearer
    at new AccessToken (/Users/sorenpeternielsen/node_modules/simple-oauth2/lib/client/access-token.js:15:27)
    at Object.AccessToken.create (/Users/sorenpeternielsen/node_modules/simple-oauth2/lib/client/access-token.js:25:12)
    at saveToken (/Users/sorenpeternielsen/nibe01/mggt.js:35:32)
    at tryCatcher (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/sorenpeternielsen/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
`

**Comment by alexandrevilain** [comment]
The same for me ...

**Comment by alexandrevilain** [comment]
The same for me but : 
`TypeError: Cannot read property 'expires_in' of undefined`

**Comment by bilalba** [comment]
Same error!

**Comment by jonathansamines** [comment]
Hi @sorenp as your stacktrace states, the errors seems to be that you are passing the `accessToken.create` function a string instead of an object (the token detail returned by your oauth-server).

```js
TypeError: Cannot assign to read only property 'expires_at' of access_token=55b687c17346ccf22bc7188c3c786c5ad110a97a&scope=notifications&token_type=bearer
```
It looks like you are passing a querystring. I can´t tell you much more with the information provided. Hope that helps.

**Comment by sorenp** [comment]
Hi @jonathansamines  - I have copied this sample code from the README:
[https://github.com/lelylan/simple-oauth2#express-and-github-example](https://github.com/lelylan/simple-oauth2#express-and-github-example)
The only changes I have done is to modify it with app ID’s and callback url.

Does the sample code from the READNME work for you?

**Comment by jonathansamines** [comment]
It seems like the github api is returning a string when the `Accept` header is not set to be `application/json`. It seems like an issue with this library, since it is assumed to be working only with json values.

Let me fix this problem. Meanwhile you can check at this branch a live example:  https://github.com/lelylan/simple-oauth2/tree/feature/normalize-config/example

**Comment by sorenp** [comment]
Hi @jonathansamines, sorry - I just saw you reply now. 

When I click
[https://github.com/lelylan/simple-oauth2/tree/feature/normalize-config/example](https://github.com/lelylan/simple-oauth2/tree/feature/normalize-config/example) i get a HTTP 404. Is the branch protected?

**Comment by jonathansamines** [comment]
Not, but was deleted. The changes are not in develop, ready to be released soon!. Please check at: https://github.com/lelylan/simple-oauth2/tree/develop/example

**Comment by mkim5** [comment]
I am getting a similar error, but with Slack oauth: 
```
/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot assign to read only property 'expires_at' of
    at new AccessToken (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/lib/client/access-token.js:15:27)
    at Object.AccessToken.create (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/lib/client/access-token.js:25:12)
    at /Users/matthewkim/dev/ppj/lib/api/apps/built-in/oauthToken.js:22:41
    at tryCatcher (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/matthewkim/dev/ppj/node_modules/simple-oauth2/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)```

**Comment by sorenp** [comment]
The develop example work for me. Thx! - look forward to the release
